### ISSUE TITLE
Issue about butterfly module.

### ISSUE THREAD

**Issue by VenciFreeman** [VenciFreeman/FFT_ChipDesign#2]
- Rotation factors parameter error;

- Assign connection error;

- Testbench input error;

- Multiplier function error.

**Comment by VenciFreeman** [comment]
> Rotation factors parameter error;

The calculation errors of the Euler formula and the representation errors of the 2's complement. And there may be problems with the use of signed format (not verified).

**Solved!**

**Comment by VenciFreeman** [comment]
> Assign connection error;

Version 3.1 solved this error. But it is still unclear why the original version is wrong. Can check again if I have time.

**Solved!**

**Comment by VenciFreeman** [comment]
> Testbench input error;

The input sequence of the time sequence is wrong, and the input data x[10] is wrong.

**Solved!**

**Comment by VenciFreeman** [comment]
> Multiplier function error.

multi module version 4.1 solved this error. Do not consider to use sequential logic shift multiplier, it will slow down the speed.

**Solved!**

**Comment by VenciFreeman** [comment]
All solved on April 20, 2020.

**Closed!**

**Comment by yslim2002** [comment]
Hi. I am now having a problem. The OpenLane tool fail to conduct the synthesis proses and error of "Redefinition of module" keep popping out. Have you been facing this problem?
